# This file was generated by liblab | https://liblab.com/

from .services.achievements import AchievementsService
from .services.automation import AutomationService
from .services.bisnode import BisnodeService
from .services.bonuschecks import BonuschecksService
from .services.challenges import ChallengesService
from .services.consents import ConsentsService
from .services.contactoverview import ContactoverviewService
from .services.contacts import ContactsService
from .services.interactions import InteractionsService
from .services.interactionschemas import InteractionschemasService
from .services.inventory import InventoryService
from .services.memberstatus import MemberstatusService
from .services.orders import OrdersService
from .services.personlookup import PersonlookupService
from .services.point_accounts import PointAccountsService
from .services.posoffers import PosoffersService
from .services.promotions import PromotionsService
from .services.sms import SmsService
from .services.stores import StoresService
from .services.target_audiences import TargetAudiencesService
from .services.tracking import TrackingService
from .services.transactions import TransactionsService
from .net.environment import Environment


class VoyadoEngage:
    def __init__(
        self, access_token: str = None, base_url: str = Environment.DEFAULT.value
    ):
        """
        Initializes VoyadoEngage the SDK class.
        """
        self.achievements = AchievementsService(base_url=base_url)
        self.automation = AutomationService(base_url=base_url)
        self.bisnode = BisnodeService(base_url=base_url)
        self.bonuschecks = BonuschecksService(base_url=base_url)
        self.challenges = ChallengesService(base_url=base_url)
        self.consents = ConsentsService(base_url=base_url)
        self.contactoverview = ContactoverviewService(base_url=base_url)
        self.contacts = ContactsService(base_url=base_url)
        self.interactions = InteractionsService(base_url=base_url)
        self.interactionschemas = InteractionschemasService(base_url=base_url)
        self.inventory = InventoryService(base_url=base_url)
        self.memberstatus = MemberstatusService(base_url=base_url)
        self.orders = OrdersService(base_url=base_url)
        self.personlookup = PersonlookupService(base_url=base_url)
        self.point_accounts = PointAccountsService(base_url=base_url)
        self.posoffers = PosoffersService(base_url=base_url)
        self.promotions = PromotionsService(base_url=base_url)
        self.sms = SmsService(base_url=base_url)
        self.stores = StoresService(base_url=base_url)
        self.target_audiences = TargetAudiencesService(base_url=base_url)
        self.tracking = TrackingService(base_url=base_url)
        self.transactions = TransactionsService(base_url=base_url)
        self.set_access_token(access_token)

    def set_base_url(self, base_url):
        """
        Sets the base URL for the entire SDK.
        """
        self.achievements.set_base_url(base_url)
        self.automation.set_base_url(base_url)
        self.bisnode.set_base_url(base_url)
        self.bonuschecks.set_base_url(base_url)
        self.challenges.set_base_url(base_url)
        self.consents.set_base_url(base_url)
        self.contactoverview.set_base_url(base_url)
        self.contacts.set_base_url(base_url)
        self.interactions.set_base_url(base_url)
        self.interactionschemas.set_base_url(base_url)
        self.inventory.set_base_url(base_url)
        self.memberstatus.set_base_url(base_url)
        self.orders.set_base_url(base_url)
        self.personlookup.set_base_url(base_url)
        self.point_accounts.set_base_url(base_url)
        self.posoffers.set_base_url(base_url)
        self.promotions.set_base_url(base_url)
        self.sms.set_base_url(base_url)
        self.stores.set_base_url(base_url)
        self.target_audiences.set_base_url(base_url)
        self.tracking.set_base_url(base_url)
        self.transactions.set_base_url(base_url)

        return self

    def set_access_token(self, access_token: str):
        """
        Sets the access token for the entire SDK.
        """
        self.achievements.set_access_token(access_token)
        self.automation.set_access_token(access_token)
        self.bisnode.set_access_token(access_token)
        self.bonuschecks.set_access_token(access_token)
        self.challenges.set_access_token(access_token)
        self.consents.set_access_token(access_token)
        self.contactoverview.set_access_token(access_token)
        self.contacts.set_access_token(access_token)
        self.interactions.set_access_token(access_token)
        self.interactionschemas.set_access_token(access_token)
        self.inventory.set_access_token(access_token)
        self.memberstatus.set_access_token(access_token)
        self.orders.set_access_token(access_token)
        self.personlookup.set_access_token(access_token)
        self.point_accounts.set_access_token(access_token)
        self.posoffers.set_access_token(access_token)
        self.promotions.set_access_token(access_token)
        self.sms.set_access_token(access_token)
        self.stores.set_access_token(access_token)
        self.target_audiences.set_access_token(access_token)
        self.tracking.set_access_token(access_token)
        self.transactions.set_access_token(access_token)

        return self


# c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
